# Use postgres/example user/password credentials
version: '3.1'

services:

  postgres:
    container_name: "postgres"
    image: mdillon/postgis
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: donde_postgress
      POSTGRES_PASSWORD: D0ND3p0stgr3s
    volumes:
        - "/var/log/postgresql"

